create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  page_key text not null unique,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

-- El acceso de escritura se realiza desde la API del servidor usando
-- SUPABASE_SERVICE_ROLE_KEY. No expongas esa llave en el navegador.
